#!/usr/bin/env python3
"""Guard: the committed dogfood manifest must match a fresh generation.

The dogfood manifest at ``site/.well-known/pagedigest.json`` and the durable
state at ``site-state/state.json`` are committed artifacts (regenerated by
hand, then reconciled against served bytes per CONTENT_HYGIENE.md). This guard
catches drift when ``site/`` content is edited without re-running the generator:
it regenerates from ``site/`` into a temporary state copy and compares
build hashes and revisions to the committed generator state, then compares
``site_rev``, ``coverage``, and entry revisions to the committed manifest.
Served-byte digests may differ after reconciliation; live verification checks
those separately. Informational timestamps are ignored.

Run it via ``./tools/run_checks.sh`` (CI runs the same). On failure, regenerate:

    cargo run --manifest-path implementations/rust-generator/Cargo.toml -- \\
        ./site --output site/.well-known/pagedigest.json \\
        --state site-state/state.json --with-digest

then reconcile against the live origin if any digest no longer matches served
bytes (CONTENT_HYGIENE.md), and commit both files.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from pagedigest import validate_manifest

ROOT = Path(__file__).resolve().parents[1]
GENERATOR_DIR = ROOT / "implementations" / "rust-generator"
SITE_DIR = ROOT / "site"
COMMITTED_MANIFEST = SITE_DIR / ".well-known" / "pagedigest.json"
COMMITTED_STATE = ROOT / "site-state" / "state.json"


def run_generator(site: Path, output: Path, state: Path) -> None:
    cmd = [
        "cargo",
        "run",
        "--quiet",
        "--",
        str(site),
        "--output",
        str(output),
        "--state",
        str(state),
        "--with-digest",
    ]
    subprocess.run(cmd, cwd=GENERATOR_DIR, check=True, capture_output=True, text=True)


def normalize(manifest: dict[str, Any]) -> dict[str, Any]:
    entries = {
        key: {"rev": value["rev"]}
        for key, value in sorted(manifest.get("entries", {}).items())
    }
    return {
        "site_rev": manifest.get("site_rev"),
        "coverage": manifest.get("coverage"),
        "entries": entries,
    }


def normalize_state(state: dict[str, Any]) -> dict[str, Any]:
    normalized = normalize(state)
    for field in ("entries", "retired"):
        normalized[field] = {
            key: {"rev": entry["rev"], "digest": entry["digest"]}
            for key, entry in state.get(field, {}).items()
        }
    return normalized


def main() -> int:
    committed_state = json.loads(COMMITTED_STATE.read_text(encoding="utf-8"))
    with tempfile.TemporaryDirectory(prefix="pagedigest-dogfood-") as tmp:
        tmp_path = Path(tmp)
        fresh_output = tmp_path / "pagedigest.json"
        state_copy = tmp_path / "state.json"
        shutil.copyfile(COMMITTED_STATE, state_copy)
        run_generator(SITE_DIR, fresh_output, state_copy)
        fresh = json.loads(fresh_output.read_text(encoding="utf-8"))
        fresh_state = json.loads(state_copy.read_text(encoding="utf-8"))

    committed = json.loads(COMMITTED_MANIFEST.read_text(encoding="utf-8"))
    if not isinstance(committed, dict):
        raise SystemExit("invalid dogfood manifest: not an object")
    if (error := validate_manifest(committed)) is not None:
        raise SystemExit(f"invalid dogfood manifest: {error}")
    if normalize_state(fresh_state) != normalize_state(committed_state) or normalize(
        fresh
    ) != normalize(committed):
        raise SystemExit(
            "dogfood manifest drift: site/.well-known/pagedigest.json does not "
            "match a fresh generation from site/. Regenerate the manifest and "
            "state, reconcile against served bytes if needed, and commit:\n"
            "  cargo run --manifest-path implementations/rust-generator/Cargo.toml "
            "-- ./site --output site/.well-known/pagedigest.json "
            "--state site-state/state.json --with-digest"
        )

    print("dogfood manifest in sync with site/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
