#!/usr/bin/env python3
"""Guard: the committed dogfood manifest must match a fresh generation.

The dogfood manifest at ``site/.well-known/pagedigest.json`` and the durable
state at ``site-state/state.json`` are committed artifacts (regenerated by
hand, then reconciled against served bytes per CONTENT_HYGIENE.md). This guard
catches drift when ``site/`` content is edited without re-running the generator:
it regenerates from ``site/`` into a temporary state copy and compares
``site_rev``, ``coverage``, and every entry's ``rev``/``digest`` to the
committed manifest. The non-deterministic ``generated`` timestamp is ignored.

Run it via ``./tools/run_checks.sh`` (CI runs the same). On failure, regenerate:

    cargo run --manifest-path implementations/rust-generator/Cargo.toml -- \\
        ./site --output site/.well-known/pagedigest.json \\
        --state site-state/state.json --with-digest

then reconcile against the live origin if any digest no longer matches served
bytes (CONTENT_HYGIENE.md), and commit both files.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
GENERATOR_DIR = ROOT / "implementations" / "rust-generator"
SITE_DIR = ROOT / "site"
COMMITTED_MANIFEST = SITE_DIR / ".well-known" / "pagedigest.json"
COMMITTED_STATE = ROOT / "site-state" / "state.json"


def run_generator(site: Path, output: Path, state: Path) -> None:
    cmd = [
        "cargo",
        "run",
        "--quiet",
        "--",
        str(site),
        "--output",
        str(output),
        "--state",
        str(state),
        "--with-digest",
    ]
    subprocess.run(cmd, cwd=GENERATOR_DIR, check=True, capture_output=True, text=True)


def normalize(manifest: dict[str, Any]) -> dict[str, Any]:
    entries = {
        key: {"rev": value["rev"], "digest": value.get("digest")}
        for key, value in sorted(manifest.get("entries", {}).items())
    }
    return {
        "site_rev": manifest.get("site_rev"),
        "coverage": manifest.get("coverage"),
        "entries": entries,
    }


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="pagedigest-dogfood-") as tmp:
        tmp_path = Path(tmp)
        fresh_output = tmp_path / "pagedigest.json"
        state_copy = tmp_path / "state.json"
        shutil.copyfile(COMMITTED_STATE, state_copy)
        run_generator(SITE_DIR, fresh_output, state_copy)
        fresh = json.loads(fresh_output.read_text(encoding="utf-8"))

    committed = json.loads(COMMITTED_MANIFEST.read_text(encoding="utf-8"))
    if normalize(fresh) != normalize(committed):
        raise SystemExit(
            "dogfood manifest drift: site/.well-known/pagedigest.json does not "
            "match a fresh generation from site/. Regenerate the manifest and "
            "state, reconcile against served bytes if needed, and commit:\n"
            "  cargo run --manifest-path implementations/rust-generator/Cargo.toml "
            "-- ./site --output site/.well-known/pagedigest.json "
            "--state site-state/state.json --with-digest"
        )

    print("dogfood manifest in sync with site/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
